# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md

footer: Be cool

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

comments: 
  enable: true
  type: valine
  nickname: taihao
  appId: bU1mmheP9KoEbUxasWEhoMNL-gzGzoHsz
  appKey: 5T6dSLSeQD0ynN6DSjwgWACg
